# Generated by Django 5.0.6 on 2024-08-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_products_color_products_condition_products_os_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='battery',
            field=models.CharField(default='Battery Capacity', max_length=100),
        ),
        migrations.AddField(
            model_name='products',
            name='features',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
