# Generated by Django 5.0.6 on 2024-08-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_products_battery_products_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='battery',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='products',
            name='color',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='condition',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='os',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='storage',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
