# Generated by Django 5.0.6 on 2024-08-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_products_battery_alter_products_color_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField()),
                ('ip_address', models.GenericIPAddressField(default='0.0.0.0')),
                ('location', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
